// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xedlszqjdplxcpydmfme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZGxzenFqZHBseGNweWRtZm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzgwMjYsImV4cCI6MjA2MTk1NDAyNn0.Fkgu0Uzf-202cOAji9dtnANARoG24hsR0j1aFCM3mN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);